version: '3.1'

services:
  web:
    build: .
    command: python3 main.py
    ports:
        - 8000:8000
    restart: always
    volumes:
      - ./main.py:/app/main.py
      - ./src/:/app/src/  
    
