version: '3.8'

services:
  web:
    container_name: fastapi_web_container
    build: .
    command: python src/main.py
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres_container
    image: postgres:13.8
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.14
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    ports:
      - "5050:80"
    restart: unless-stopped

  redis:
    container_name: fastapi_redis_container
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    env_file:
      - ./.env
    environment:
      REDIS_HOSTS: ${REDIS_HOSTS}
      HTTP_USER: ${HTTP_USER}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  postgres:
  pgadmin:
  redis: