version: '3.8'

services:
  web:
    container_name: fastapi_web_container
    build: .
    command: python main.py
    volumes:
      - ./main.py:/app/main.py
      - ./db:/app/db
      - ./my_redis:/app/my_redis
      - ./schemas:/app/schemas
      - ./settings:/app/settings
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    env_file:
      - ./.env
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres_container
    image: postgres:13.8
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.14
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    ports:
      - ${PGADMIN_PORT}:80
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_fastapi_db
    env_file:
      - ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/var/lib/redis/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      REDIS_HOSTS: "local:redis:6379"
      HTTP_USER: "zxc"
      HTTP_PASSWORD: "zxc"
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  postgres:
  pgadmin:
  redis: