"""migration_1

Revision ID: 554ead78c4e6
Revises: 94f39618bb87
Create Date: 2022-11-02 18:19:06.340470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554ead78c4e6'
down_revision = '94f39618bb87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('right_answer', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
