"""migration_11

Revision ID: 626d7ed2111e
Revises: 642b62721e25
Create Date: 2022-10-23 09:31:36.023166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626d7ed2111e'
down_revision = '642b62721e25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
