"""migration_1

Revision ID: 712aa690e361
Revises: f719034207c3
Create Date: 2022-11-02 17:52:25.077771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '712aa690e361'
down_revision = 'f719034207c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_option_id', table_name='option')
    op.drop_table('option')
    op.add_column('question', sa.Column('questions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('question', sa.Column('right_answer', sa.Integer(), nullable=True))
    op.drop_column('question', 'question')
    op.drop_column('question', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('question', 'right_answer')
    op.drop_column('question', 'questions')
    op.create_table('option',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('option', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_right', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='option_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='option_pkey')
    )
    op.create_index('ix_option_id', 'option', ['id'], unique=False)
    # ### end Alembic commands ###
