"""migration_2

Revision ID: 8e650c385b4f
Revises: d9e8dacd3180
Create Date: 2022-10-24 15:40:15.524399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e650c385b4f'
down_revision = 'd9e8dacd3180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_members', 'is_admin')
    # ### end Alembic commands ###
