"""migration_1

Revision ID: 94f39618bb87
Revises: 712aa690e361
Create Date: 2022-11-02 18:17:20.750597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94f39618bb87'
down_revision = '712aa690e361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question', sa.String(), nullable=True))
    op.add_column('question', sa.Column('options', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('question', 'questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('questions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('question', 'options')
    op.drop_column('question', 'question')
    # ### end Alembic commands ###
