"""migration_1

Revision ID: 9c4cf22b2244
Revises: f3643c05d2df
Create Date: 2022-10-29 23:09:30.052753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4cf22b2244'
down_revision = 'f3643c05d2df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avarage_users_mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('right_answers', sa.Integer(), nullable=True),
    sa.Column('avarage_mark', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avarage_users_mark_id'), 'avarage_users_mark', ['id'], unique=False)
    op.create_table('quiz_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('right_answers', sa.Integer(), nullable=True),
    sa.Column('avarage_mark', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_result_id'), 'quiz_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_result_id'), table_name='quiz_result')
    op.drop_table('quiz_result')
    op.drop_index(op.f('ix_avarage_users_mark_id'), table_name='avarage_users_mark')
    op.drop_table('avarage_users_mark')
    # ### end Alembic commands ###
