"""migration_1

Revision ID: ccba048477df
Revises: 
Create Date: 2022-11-05 09:54:52.229725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccba048477df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_result', sa.Column('mark', sa.Float(), nullable=True))
    op.drop_column('quiz_result', 'avarage_mark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_result', sa.Column('avarage_mark', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('quiz_result', 'mark')
    # ### end Alembic commands ###
