"""migration_1

Revision ID: f719034207c3
Revises: 9c4cf22b2244
Create Date: 2022-10-29 23:57:33.102998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f719034207c3'
down_revision = '9c4cf22b2244'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avarage_users_mark', sa.Column('quizzes_passed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avarage_users_mark', 'quizzes_passed')
    # ### end Alembic commands ###
